TARGET = do-op
SOURCES = main.c ft_str.c ft_atoi.c calculator.c operators.c
CC = gcc -Wall -Wextra -Werror

all: ${TARGET}

${TARGET}:
	${CC} -o ${TARGET} ${SOURCES}

clean:
	rm -f do-op

re: clean all
